TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += hlx503.db
DB += hlx503_itc.db

#protocol files
DATA += hlx503_itc.proto

#=======================================
include $(TOP)/configure/RULES
