TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += hlx503.db

#protocol files
# DATA += hlx503.proto

#=======================================
include $(TOP)/configure/RULES
