TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += hlx503.db

#protocol files

#=======================================
include $(TOP)/configure/RULES
